apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-eks
  namespace: argocd
spec:
  destination:
    namespace: proyecto-integrado
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoCD
    repoURL: https://github.com/robertorodriguez98/proyecto-integrado.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
