apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: sample-instance

spec:
  forProvider:
    region: eu-south-2
    imageId: ami-07b717f30bab3cc32
    instanceType: t3.micro
    keyName: claveaws
    securityGroupIds: ["sg-0c3af855d7095afeb"]
    userData: IyEvYmluL2Jhc2gKZG5mIHVwZGF0ZQpkbmYgaW5zdGFsbCBodHRwZCAteQplY2hvICJQYWdpbmEgZGUgcHJ1ZWJhcyB0YWwiID4gL3Zhci93d3cvaHRtbC9pbmRleC5odG1sCnN5c3RlbWN0bCByZXN0YXJ0IGh0dHBk
    blockDeviceMappings:
      - deviceName:  /dev/xvda
        ebs:
          volumeSize: 15
          deleteOnTermination: true
  providerConfigRef:
    name: default