apiVersion: prodready.cluster/v1alpha1
kind: ClusterClaim
metadata:
  name: proyecto
  labels:
    cluster-owner: robertorm
spec:
  id: proyecto
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 2
