apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: loadbalancer-aplicacion-remoto
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: aplicacion
      spec:
        type: LoadBalancer
        selector:
          app: aplicacion
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
  providerConfigRef:
    name: kubernetes-provider